#!/usr/bin/env bash
language: python
python:
  - "3.6"
install:
  - wget https://repo.continuum.io/archive/Anaconda3-5.2.0-Linux-x86_64.sh
  - bash Anaconda3-5.2.0-Linux-x86_64.sh -b -p $HOME/anaconda3
  - export PATH="$HOME/anaconda3/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - pip install -r requirements.txt
script:
  - pip install -e .
  - cd generalframework/test
  - pwd
  - which python
  - which pytest
  - python -c "import pandas as pd;print(pd.__version__)"
  - python -m pytest