Arch:
  name: deeplabenet
  num_classes: 19

Optim:
  name: Adam
  lr: 0.0005

Scheduler:
  name: MultiStepLR
  milestones: [10,20,30,40,50,60,70,80,90]
  gamma: 0.7


Dataset:
  root_dir: dataset/Cityscapes
  pin_memory: False
  image_size: ( 128, 256 )
  augmentations:

Lab_Dataloader:
  pin_memory: False
  batch_size: 1
  num_workers: 0
  shuffle: True
  drop_last: True

Unlab_Dataloader:
  pin_memory: False
  batch_size: 1
  num_workers: 0
  shuffle: True
  drop_last: True

Trainer:
  max_epoch: 100
  save_dir: tmp/cotraining
  device: cuda:0
#  axises:
  metricname: metrics.csv
  lambda_cot_max: 1
  lambda_adv_max: 0.05
  ramp_up_mult: -5
  epoch_max_ramp: 80

Loss:
  name: cross_entropy
  weight: [  3.3632, 14.0408,  4.9860, 39.2617, 36.5217, 32.8975, 46.2848,
            40.6888,  6.6957, 33.5658, 18.4602, 32.9788, 47.6773, 12.7070, 45.2075,
            45.7849, 45.8268, 48.4074, 42.7600]


StartTraining:
  train_jsd: True
  train_adv: True
  save_train: True
  save_val: True