Arch:
  name: unet
  num_classes: 4

Optim:
  name: Adam
  lr: 0.001

Scheduler:
  name: MultiStepLR
  milestones: [10,20,30,40,50,60,70,80,90]
  gamma: 0.8


Dataset:
  root_dir: dataset/ACDC-all
  subfolders: ['img','gt']
  transform: segment_transform((256,256))
  augment: PILaugment
  pin_memory: False

Lab_Dataloader:
  pin_memory: False
  batch_size: 2
  num_workers: 2
  shuffle: True
  drop_last: True
  batch_sampler: [PatientSampler,
                  {grp_regex: '(patient\d+_\d+)_\d+',shuffle: False}]

Unlab_Dataloader:
  pin_memory: False
  batch_size: 4
  num_workers: 4
  shuffle: True
  drop_last: True


Trainer:
  max_epoch: 100
  save_dir: tmp/vat
  device: cuda
  axises: [1,2,3]
  metricname: metrics.csv
  lambda_adv_max: 0.5
  ramp_up_mult: -5
  epoch_max_ramp: 80
#  checkpoint: archives/cardiac/unet_No_agument/FS_fulldata/best.pth

Loss:
  name: cross_entropy
  weight: [1, 1, 1, 1]

StartTraining:
  train_adv: True
  save_train: True
  save_val: True