Arch:
  name: unet
  num_classes: 4

Optim:
  name: Adam
  lr: 0.0005

Scheduler:
  name: MultiStepLR
  milestones: [10,20,30,40,50,60,70,80,90]
  gamma: 0.7


Dataset:
  root_dir: dataset/ACDC-all
  subfolders: ['img','gt']
  transform: segment_transform((256,256))
  augment: PILaugment
  pin_memory: False

Lab_Dataloader:
  pin_memory: False
  batch_size: 2
  num_workers: 2
  shuffle: False
  drop_last: True
  batch_sampler: [PatientSampler,
                  {grp_regex: '(patient\d+_\d+)_\d+',shuffle: False}]

Unlab_Dataloader:
  pin_memory: False
  batch_size: 4
  num_workers: 4
  shuffle: False
  drop_last: True

Trainer:
  max_epoch: 100
  save_dir: tmp/cotraining
  device: cuda
  axises: [1,2,3]
  metricname: metrics.csv
  lambda_cot_max: 1
  lambda_adv_max: 0.05
  ramp_up_mult: -5
  epoch_max_ramp: 80

Loss:
  name: cross_entropy
  weight: [1, 1, 1, 1]

StartTraining:
  train_jsd: False
  train_adv: False
  save_train: False
  save_val: True