Arch:
  name: unet
  num_classes: 4

Optim:
  name: Adam
  lr: 0.001

Scheduler:
  name: MultiStepLR
  milestones: [10,20,30,40,50,60,70,80,90]
  gamma: 0.7

Dataset:
  root_dir: dataset/ACDC-all
  subfolders: ['img','gt']
  transform: segment_transform((256,256))
  augment: PILaugment
  pin_memory: False

Dataloader:
  pin_memory: True
  batch_size: 2
  num_workers: 2
  shuffle: True
  drop_last: True
  batch_sampler: [PatientSampler,
                  {grp_regex: '(patient\d+_\d+)_\d+',shuffle: False}]

Trainer:
  max_epoch: 100
  save_dir: tmp/classification
  device: cuda
  axises: [1,2,3]
  metricname: metrics.csv

StartTraining:
  save_train: False
  save_val: False

Loss:
  name: cross_entropy
  weight: [1, 1, 1, 1]