Arch:
  name: enet
  num_classes: 4

Optim:
  name: Adam
  lr: 0.005
#  weight_decay: 0.00002

Scheduler:
  name: StepLR
  step_size: 30
  gamma: 0.1


Dataset:
  root_dir: dataset/ACDC-all
  subfolders: ['img','gt']
  transform: segment_transform((256,256))
  augment: None
  pin_memory: False

Lab_Dataloader:
  pin_memory: False
  batch_size: 2
  num_workers: 2
  shuffle: True
  drop_last: True
  batch_sampler: [PatientSampler,
                  {grp_regex: '(patient\d+_\d+)_\d+',shuffle: False}]

Lab_Partitions:
  label: [[1,101],[1,101]]
  unlabel: [50,100]


Unlab_Dataloader:
  pin_memory: False
  batch_size: 2
  num_workers: 2
  shuffle: True
  drop_last: True

Trainer:
  max_epoch: 75
  save_dir: tmp/ACDC_cotraining
  device: cuda:0
  axises: [1,2,3]
  metricname: metrics.csv
  use_tqdm: True

Adv_Training:
  eplision:  0.001
  fsgm_ratio: 1
  axises: [0,1,2,3]

Cot_Scheduler:
  name: RampScheduler
  begin_epoch: 0
  max_epoch: 80
  max_value: 1.0
  ramp_mult: -5

Adv_Scheduler:
  name: RampScheduler
  begin_epoch: 10
  max_epoch: 80
  max_value: 0.5
  ramp_mult: -5

Loss:
  name: cross_entropy
  weight: [1, 1, 1, 1]

StartTraining:
  train_jsd: False
  train_adv: False
  save_train: False
  save_val: False
  augment_labeled_data: False
  augment_unlabeled_data: False