Arch:
  name: unet
  num_classes: 4

Optim:
  name: Adam
  lr: 0.0005

Scheduler:
  name: MultiStepLR
  milestones: [10,20,30,40,50,60,70,80,90]
  gamma: 0.7

Dataset:
  root_dir: dataset/ACDC-all
  subfolders: ['img','gt']
  transform: segment_transform((256,256))
  augment: PILaugment
  pin_memory: False

Lab_Dataloader:
  pin_memory: False
  batch_size: 2
  num_workers: 2
  shuffle: True
  drop_last: True
  batch_sampler: [PatientSampler,
                  {grp_regex: '(patient\d+_\d+)_\d+',shuffle: False}]

Unlab_Dataloader:
  pin_memory: False
  batch_size: 2
  num_workers: 2
  shuffle: False
  drop_last: True

Trainer:
  max_epoch: 100
  save_dir: tmp/vat
  device: cuda:0
  axises: [1,2,3]
  metricname: metrics.csv


Loss:
  name: cross_entropy
  weight: [1, 1, 1, 1]

StartTraining:
  train_adv: True
  save_train: False
  save_val: False
  use_tqdm: True

Adv_Scheduler:
  name: RampScheduler
  begin_epoch: 10
  max_epoch: 80
  max_value: 0.5
  ramp_mult: -5

Adv_Training:
  eplision:  0.001
  vat_axises: [0,1,2,3]
  vat_lossname: kl
  ip: 1

Lab_Partitions:
  label: [[1,61]]
  unlabel: [61,100]